//go:generate goldigen --in "config/types.yml" --out "dependency_injection.go" --package github.com/fgrosse/servo/example --function RegisterTypes --overwrite --nointeraction
package example

import (
	"github.com/fgrosse/goldi"
	"github.com/fgrosse/servo/example/endpoints"
)

// RegisterTypes registers all types that have been defined in the file "config/types.yml"
//
// DO NOT EDIT THIS FILE: it has been generated by goldigen v0.9.0.
// It is however good practice to put this file under version control.
// See https://github.com/fgrosse/goldi for what is going on here.
func RegisterTypes(types goldi.TypeRegistry) {
	types.Register("greet_user_endpoint", goldi.NewFuncType(endpoints.GreetUserEndpoint))
	types.Register("hello_world_endpoint", goldi.NewFuncType(endpoints.HelloWorldEndpoint))
}
