hello_world_endpoint:
    path: /

greet_user_endpoint:
    path: /hello/{name}

controller_endpoint:
    path: /controller

composed_endpoint:
    path: /composed

container_aware_endpoint:
    path: /container

error_endpoint:
    path: /error
