types:
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    # Oridnary type definitions:             #
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    my_controller:
        package: github.com/fgrosse/servo/example/endpoints
        type:    FancyController
        args:
            - "@my_service_client"

    my_service_client:
        package: github.com/fgrosse/servo/example/lib
        type:    ServiceClient # TODO introduce some semantic for guaranteeing an interface for defined types
        factory: NewMockServiceClient
        args:
            - "%my_app.some_parameter%"

    my_logger:
        factory: "@logger_provider::GetLogger"
        args:    [ my_app ]
        calls: # TODO implement this in goldi
            - [ SetLevel, [ 10 ] ] # 10 = LevelTrace

    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    # Endpoints that are used by the router: #
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    hello_world_endpoint:
        package: github.com/fgrosse/servo/example/endpoints
        func:    HelloWorldEndpoint

    greet_user_endpoint:
        package: github.com/fgrosse/servo/example/endpoints
        func:    GreetUserEndpoint

    controller_endpoint:
        func:    @my_controller::FancyAction

    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    # Endpoints can also be composed:        #
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    composed_endpoint:
        package: github.com/fgrosse/servo/handlers
        factory: ComposedHandler
        args:
            - @my_controller::OuterHandlerAction
            - @my_controller::SecondHandlerAction
            - @my_controller::FancyAction

    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    # Define our own http handler chain      #
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
    my_app.logging_adapter:
        package: github.com/fgrosse/servo/handlers
        factory: LoggingAdapter
        args:    [ @my_logger ]

    my_app.http_handler_func:
        package: github.com/fgrosse/servo/handlers
        factory: ComposedHandler
        args:
            # TODO add more to the chain
            - @servo.routing.router::ServeHTTP

    kernel.http_handler:
        package: github.com/fgrosse/servo/handlers
        factory: AdapterHandler
        args:
            - @my_app.logging_adapter
            - @my_app.http_handler_func
