types:
    hello_world_endpoint:
        package: github.com/fgrosse/servo/example/endpoints
        func:    HelloWorldEndpoint

    greet_user_endpoint:
        package: github.com/fgrosse/servo/example/endpoints
        func:    GreetUserEndpoint
