language: go
sudo: false

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - tip

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
  - go get -v -t ./...

script:
  - go test .               -cover -coverprofile servo.coverprofile
  - go test ./configuration -cover -coverprofile configuration.coverprofile 

after_script:
  - gover
  - goveralls -coverprofile=gover.coverprofile -repotoken $COVERALLS_TOKEN
