language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - tip

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - go get -v ./...

script:
  - go test ./tests -cover -coverpkg github.com/fgrosse/servo -coverprofile servo.coverprofile
  - gover
  - goveralls -coverprofile=gover.coverprofile -repotoken $COVERALLS_TOKEN || /bin/true
