package servo

import (
	"github.com/fgrosse/goldi"
)

// registerInternalTypes registers all types that have been defined in the file "servo_types.yml"
//
// DO NOT EDIT THIS FILE: it has been generated by goldigen v0.1.0.
// It is however good practice to put this file under version control.
// See https://github.com/FGrosse/goldi for what is going on here.
func registerInternalTypes(types goldi.TypeRegistry) {
	types.RegisterType("kernel.server", NewHTTPServer, "%servo.listen%", "@kernel.http_handler")
}
