//go:generate goldigen --in "types.yml" --out "types.go" --package github.com/fgrosse/servo/bundles/routing --function RegisterTypes --overwrite --nointeraction
package routing

import (
	"github.com/fgrosse/goldi"
)

// RegisterTypes registers all types that have been defined in the file "types.yml"
//
// DO NOT EDIT THIS FILE: it has been generated by goldigen v0.9.0.
// It is however good practice to put this file under version control.
// See https://github.com/fgrosse/goldi for what is going on here.
func RegisterTypes(types goldi.TypeRegistry) {
	types.Register("kernel.http_handler", goldi.NewTypeAlias("servo.routing.router"))
	types.Register("servo.routing.loader", goldi.NewStructType(new(Loader)))
	types.Register("servo.routing.router", goldi.NewType(NewRouter, "@servo.routing.loader", "@container"))
}
