//go:generate goldigen --in "types.yml" --out "types.go" --package github.com/fgrosse/servo/bundles/logxi --function RegisterTypes --overwrite --nointeraction
package logxi

import (
	"github.com/fgrosse/goldi"
)

// RegisterTypes registers all types that have been defined in the file "types.yml"
//
// DO NOT EDIT THIS FILE: it has been generated by goldigen v0.9.8.
// It is however good practice to put this file under version control.
// See https://github.com/fgrosse/goldi for what is going on here.
func RegisterTypes(types goldi.TypeRegistry) {
	types.RegisterAll(map[string]goldi.TypeFactory{
		"logger_provider":       goldi.NewAliasType("logxi.logger_provider"),
		"logxi.configurator":    goldi.NewType(NewLoggerConfigurator, "%logxi.level%"),
		"logxi.logger_provider": goldi.NewConfiguredType(
		goldi.NewStructType(new(LoggerProvider)),
		"logxi.configurator", "Configure",
	),
	})
}
