//go:generate goldigen --in "types.yml" --out "types.go" --package github.com/fgrosse/servo/bundles/logxi --function RegisterTypes --overwrite --nointeraction
package logxi

import (
	"github.com/fgrosse/goldi"
	"github.com/mgutz/logxi/v1"
)

// RegisterTypes registers all types that have been defined in the file "types.yml"
//
// DO NOT EDIT THIS FILE: it has been generated by goldigen v0.9.0.
// It is however good practice to put this file under version control.
// See https://github.com/fgrosse/goldi for what is going on here.
func RegisterTypes(types goldi.TypeRegistry) {
	types.Register("logger", goldi.NewConfiguredType(
		goldi.NewType(log.New, "servo"),
		"logxi.configurator", "Configure",
	))
	types.Register("logxi.configurator", goldi.NewType(NewLoggerConfigurator, "%logxi.level%"))
}
